language: go

go:
  - 1.7.1
  - 1.7.3
  - 1.7.4
  - 1.8
  - 1.9
  - tip
  
matrix:
  allow_failures:
    - go: tip
  fast_finish: true    
install:
  - mkdir -p $GOPATH/src/github.com/pubnub
  - ln -s $GOPATH/src/github.com/beeman/pubnub-go-v3
  - go get -t -v ./messaging/...
  - go get github.com/wadey/gocovmerge

script:
  - bash ./test.sh

after_success:
    - bash <(curl -s https://codecov.io/bash)
